
package com.app.appname.utilities;

import org.openqa.selenium.WebDriver;

import net.serenitybdd.core.Serenity;
import org.apache.log4j.Logger;

public class DriverGetterSetter {

	private static WebDriver driver;
	static Logger logger = Logger.getLogger(DriverGetterSetter.class);
	
	/**
	 **********************************************************************
	 * @Function Name : setDriver
	 * @Description : Get Driver Instance as generated by the Framework
	 * @Param : null
	 * @Return : null
	 ***********************************************************************
	 */
	public static WebDriver getDriver() {
		//logger.info("getDriver: Getting driver ");
		if (driver == null) {
			setDriver();
		}
		return driver;
	}

	/**
	 **********************************************************************
	 * @Function Name : setDriver
	 * @Description : Set Driver Instance as generated by the Framework
	 * @Param : null
	 * @Return : null
	 ***********************************************************************
	 */
	private static void setDriver() {
		//logger.info("setDriver: Setting driver ");
		DriverGetterSetter.driver = Serenity.getWebdriverManager().getWebdriver();
	}

}
